version: "2"

networks:
  appnet:
    external: true

services:
  gqlblog:
    build: .
    container_name: webhooks
    volumes:
      - ./logs:/opt/nodeapp/logs
    networks:
      - appnet
    environment:
      - "VIRTUAL_HOST=dfg.rocks"
      - "VIRTUAL_PORT=3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webhooks.rule=Host(`webhooks.dfg.rocks`)"
      - "traefik.http.services.webhooks.loadbalancer.server.port=3000"
      - "traefik.http.routers.webhooks.entrypoints=web"
      - "traefik.http.routers.webhooks.tls.certresolver=mydnschallenge"
      - "traefik.http.middlewares.webhooks.redirectscheme.scheme=https"
      # - "traefik.http.routers.webhooks.tls.domains[0].main=dfg.rocks"
      # - "traefik.http.routers.webhooks.tls.domains[0].sans=*.dfg.rocks"
